# Generated by Django 4.1.13 on 2024-02-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.CharField(max_length=255),
        ),
    ]
