# Generated by Django 4.1.13 on 2024-02-12 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_tag_item_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="desired_stock",
            field=models.IntegerField(
                default=0, help_text="Desired stock level to maintain."
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="min_stock",
            field=models.IntegerField(
                default=0, help_text="Minimum stock level before reordering."
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_items",
                to="backend.item",
            ),
        ),
    ]
